# Generated by Django 4.2.1 on 2023-05-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230423_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('how_many_people', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
