# Generated by Django 3.2.18 on 2023-04-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзину пользователей', 'verbose_name_plural': 'Корзина пользователей'},
        ),
        migrations.AlterModelOptions(
            name='dishcategory',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
