# Generated by Django 3.2.18 on 2023-05-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_auto_20230422_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
