# Generated by Django 4.2.3 on 2023-08-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_dish_weight'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dish',
            table='Dish',
        ),
    ]
