# Generated by Django 4.2.3 on 2023-08-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_alter_dish_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dish',
            table=None,
        ),
    ]
